[project]
name = "mito-volume"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathlib>=1.0.1",
    "polars>=1.38.1",
    "pyqt6>=6.10.2",
    "xlsxwriter>=3.2.9",
]
